version: '3.4'

services:
  adapter:
    image: 127.0.0.1:5001/hololens-adapter
    build: ./
    volumes:
      - ./data/:/data/
#      - /mnt/glusterfs/dtz/node-red/hololens-adapter/data/:/data/
    ports:
      - 1880:1880
    network_mode: host
    deploy:
      placement:
        constraints: [node.hostname == il071]
      resources:
        limits:
          cpus: "1"
          memory: 1G
      replicas: 1
      update_config:
        parallelism: 2
        delay: 10s
      restart_policy:
        condition: on-failure

